### ISSUE TITLE
City filter displaying empty brackets

### ISSUE THREAD

**Issue by SeptimusVII** [Web-Ex-Machina/contao-geodata#3]
![image](https://user-images.githubusercontent.com/28646786/215556934-25dcb98a-7147-4319-97ab-a850cc19b78a.png)

City filters sometimes display empty bracket after their label. they're originaly meant to display part of the corresponding postal code and comes fromold Altrad bundle. Maybbe we should get rid of it, @LupusVII ? If not, brackets should not be displayed if they're empty

ps: this is no frontend/template issue, the label comes already constructed in the data

**Comment by ChipsVII** [comment]
Here is the fix commit : https://github.com/Web-Ex-Machina/contao-geodata/pull/1/commits/97eab0e68fac678b1af635760eb90fa516095277

If a location's `admin_lvl_2` property has a value, it is displayed in the city filter. If empty, no brackets are included.
