### ISSUE TITLE
make matching options label for list and filters fields in map module

### ISSUE THREAD

**Issue by SeptimusVII** [Web-Ex-Machina/contao-geodata#5]
![image](https://user-images.githubusercontent.com/28646786/215747825-8a7ff6db-87e9-447d-9dfb-2cee8e097370.png)
![image](https://user-images.githubusercontent.com/28646786/215747847-133e07d7-9a53-4c55-981a-f18f7072ac6e.png)

filters options needs to be uniform with the list's ones

list:
- no list 
- right panel
- below map

filters 
- no filters 
- left panel
- above map --> new var check in template at l.7, for value "above"
- below map --> make sure to change the variable check in mod_wem_geodata_map.html5, l.73 (there's a TODO quote about it)

**Comment by SeptimusVII** [comment]
![image](https://user-images.githubusercontent.com/28646786/216070130-475847b9-fbdb-4c2a-9593-b254488c18e0.png)

@ChipsVII filters displays rightpanel instead of leftpanel, and miss translations (as list field)

**Comment by ChipsVII** [comment]
Is it still an issue ? Or can I close this one ?

**Comment by SeptimusVII** [comment]
> 

can be closed
